[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "modelbuilder"
version = "0.1.0"
description = "Writes LLM in ONNX format."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "ml_dtypes",
    "numpy>=2.1",
    "onnx>=1.22",
    "onnxscript",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "black",
    "huggingface_hub",
    "onnxruntime>=1.28",
    "onnxruntime-genai==0.15.1",
    "openpyxl",
    "pandas",
    "peft",
    "pytest>=8",
    "py-cpuinfo",
    "pytest-cov",
    "pytest-subtests",
    "pytest-timeout",
    "ruff",
    "tabulate",
    "transformers",
]
doc = [
    "furo",
    "sphinx>=7",
    "sphinx-copybutton",
    "sphinx-gallery",
    "matplotlib",
]

[tool.black]
line-length = 140
target-version = ["py310", "py311", "py312", "py313", "py314"]
skip-magic-trailing-comma = true

[tool.ruff]
line-length = 140

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501", "I001"]
